//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examenfinal1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visita
    {
        public int idVisita { get; set; }
        public string motivo_visita { get; set; }
        public string nombre_completo { get; set; }
        public Nullable<System.DateTime> h_entrada { get; set; }
        public Nullable<System.DateTime> h_salida { get; set; }
        public string m_recibio { get; set; }
        public Nullable<int> idMiembro { get; set; }
    
        public virtual Miembro Miembro { get; set; }
    }
}
